variables:
    REPO: trasioteam/taref-dev

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

taref-dev-doxygen:
    variables:
        BRANCH: teep-master
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:doxygen ./doxygen
        - docker push ${REPO}:doxygen
        - docker run --name $CI_PIPELINE_ID -d ${REPO}:doxygen
        - docker wait $CI_PIPELINE_ID
        - docker cp $CI_PIPELINE_ID:/home/user/ta-ref/docs/ta-ref.pdf $CI_PROJECT_DIR/ta-ref.pdf
    artifacts:
        paths:
            - $CI_PROJECT_DIR/ta-ref.pdf
        expire_in: 1 week

taref-dev-sgx_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell115
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:sgx-teep-device ./sgx/teep-device-dev
        - docker push ${REPO}:sgx-teep-device

taref-dev-optee_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:optee-teep-device ./optee/teep-device-dev
        - docker push ${REPO}:optee-teep-device

taref-dev-keystone_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell121
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:keystone-teep-device ./keystone/teep-device-dev
        - docker push ${REPO}:keystone-teep-device
