variables:
    REPO: trasioteam/taref-dev

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

stages:
    - create-docker
    - push-public

taref-dev-doxygen:
    stage: create-docker
    variables:
        BRANCH: teep-device-dev-keystone-1.0.0
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:doxygen ./doxygen

taref-dev-sgx_teep-device:
    stage: create-docker
    variables:
        BRANCH: teep-device-dev-keystone-1.0.0
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:sgx-teep-device ./sgx/teep-device-dev

taref-dev-optee_teep-device:
    stage: create-docker
    variables:
        BRANCH: teep-device-dev-keystone-1.0.0
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:optee-teep-device ./optee/teep-device-dev

taref-dev-keystone_teep-device:
    stage: create-docker
    variables:
        BRANCH: teep-device-dev-keystone-1.0.0
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:keystone-teep-device ./keystone/teep-device-dev

docker-push-public:
    stage: push-public
    tags:
        - shell117
    script:
        - docker push ${REPO}:doxygen
        - docker push ${REPO}:sgx-teep-device
        - docker push ${REPO}:optee-teep-device
        - docker push ${REPO}:keystone-teep-device
