variables:
    REPO: trasioteam/taref-dev

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

taref-dev-doxygen:
    variables:
        BRANCH: teep-master
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:doxygen ./doxygen
        - docker push ${REPO}:doxygen

taref-dev-sgx_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell115
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:sgx-teep-device ./sgx/teep-device-dev
        - docker push ${REPO}:sgx-teep-device

taref-dev-optee_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:optee-teep-device ./optee/teep-device-dev
        - docker push ${REPO}:optee-teep-device

taref-dev-keystone_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell121
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:keystone-teep-device ./keystone/teep-device-dev
        - docker push ${REPO}:keystone-teep-device
