variables:
    REPO: trasioteam/taref-dev
    DOCS_DIR: /home/user/ta-ref/docs 

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

taref-dev-doxygen:
    variables:
        BRANCH: teep-master
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:doxygen ./doxygen
        - cp ${DOCS_DIR}/ta-ref.pdf $CI_PROJECT_DIR
        - docker push ${REPO}:doxygen
    artifacts:
        paths:
            - ta-ref.pdf
        expire_in: 1 week

taref-dev-sgx_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell115
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:sgx-teep-device ./sgx/teep-device-dev
        - docker push ${REPO}:sgx-teep-device

taref-dev-optee_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell117
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:optee-teep-device ./optee/teep-device-dev
        - docker push ${REPO}:optee-teep-device

taref-dev-keystone_teep-device:
    variables:
        BRANCH: teep-master
    tags:
        - shell121
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:keystone-teep-device ./keystone/teep-device-dev
        - docker push ${REPO}:keystone-teep-device
